name: aedex
description: Enable direct peer-to-peer trading of digital assets on the Archethic blockchain, eliminating the need for centralized intermediaries.
publish_to: "none"

version: 0.9.1+51

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  archethic_dapp_framework_flutter: ^1.1.0
  #archethic_dapp_framework_flutter:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-dapp-framework-flutter.git
  #    ref: web_extension_support
  #archethic_dapp_framework_flutter:
  #  path: ../archethic-dapp-framework-flutter

  # A client dart library to interact with Archethic Wallet RPC API.
  archethic_wallet_client: ^1.2.0
  #archethic_wallet_client:
  #  git:
  #    url: https://github.com/archethic-foundation/archethic-wallet-client-dart.git
  #    ref: web_extension_support
  # archethic_wallet_client:
  #   path: ../archethic-wallet-client-dart

  # Collections and utilities functions and classes related to collections.
  collection: ^1.18.0

  # The decimal package allows you to deal with decimal numbers without losing precision
  decimal: ^2.3.3

  # A new flutter package to display notifications on top of the screen, full customizable with built-in themes
  elegant_notification: ^2.1.0

  # A component that provides flip card animation. It could be used for hide and show details of a product.
  flip_card: ^0.7.0

  flutter:
    sdk: flutter

  # Add beautiful animated effects & builders in Flutter, via an easy, customizable, unified API.
  flutter_animate: ^4.5.0

  # Makes in-text links clickable
  flutter_linkify: ^6.0.0

  flutter_localizations:
    sdk: flutter

  # Customize Flutter's default white native splash screen with background color and splash image. Supports dark mode, full screen, and more.
  flutter_native_splash: ^2.4.0

  # State management
  flutter_riverpod: ^2.5.1

  # An SVG rendering and widget library for Flutter, which allows painting and displaying Scalable Vector Graphics 1.1 files.
  flutter_svg: ^2.0.10+1

  # Library to create Beautiful and Customized Tab/Toggle Widget on Flutter
  flutter_toggle_tab: ^1.4.1

  # Annotations for freezed
  freezed_annotation: ^2.4.1

  # A declarative router for Flutter based on Navigation 2 supporting deep linking, data-driven routes and more
  go_router: ^13.2.1

  # Gradient borders for inputs and containers. Borders package integrated with a basic flutter widgets as a container and input decorations. Easy in use, platform independent.
  gradient_borders: ^1.0.0

  # Hive is a lightweight and blazing fast key-value database written in pure Dart
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Contains code to deal with internationalized/localized messages, date and number formatting and parsing, bi-directional text, and other internationalization issues.
  intl: ^0.18.0

  # Classes and helper functions that support JSON code generation via the `json_serializable` package.
  json_annotation: ^4.8.1

  # A Flutter plugin for rendering an animated and customizable starfield on a dark background.
  lit_starfield: ^0.1.1

  # Flutter plugin for getting commonly used locations on host platform file systems, such as the temp and app data directories.
  path_provider: ^2.1.2

  # A package exposing annotations for riverpod_generator
  riverpod_annotation: ^2.3.5

  # Flutter plugin for launching a URL. Supports web, phone, SMS, and email schemes
  url_launcher: ^6.2.5

  # Flutter package that allows setting the web app URL strategy with a single line of code.
  url_strategy: ^0.2.0

  # UUID generator
  uuid: ^4.3.3

dev_dependencies:
  # A build system for Dart code generation and modular compilation.
  build_runner: ^2.4.6
  # Code generation for immutable classes that has a simple syntax/API without compromising on the features.
  daunused: ^1.3.0
  dependency_validator: ^3.2.3
  freezed: ^2.4.7
  # Extension for Hive. Automatically generates TypeAdapters to store any class.
  hive_generator: ^2.0.1
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^6.7.1
  # A code generator for Riverpod. This both simplifies the syntax empowers it, such as allowing stateful hot-reload.
  riverpod_generator: ^2.4.0
  # A full featured library for writing and running Dart tests across platforms.
  test: ^1.25.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/bc-logos/
    - lib/domain/repositories/common_bases.json
    - lib/domain/repositories/config.json
    - lib/domain/repositories/blockchains_list.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf
    - family: Iconsax
      fonts:
        - asset: assets/fonts/Iconsax.ttf
    - family: PPTelegraf
      fonts:
        - asset: assets/fonts/PPTelegraf-Ultralight.otf
          weight: 200
        - asset: assets/fonts/PPTelegraf-Light.otf
          weight: 300
        - asset: assets/fonts/PPTelegraf-Regular.otf
          weight: 400
        - asset: assets/fonts/PPTelegraf-Medium.otf
          weight: 500
        - asset: assets/fonts/PPTelegraf-Semibold.otf
          weight: 600
        - asset: assets/fonts/PPTelegraf-Bold.otf
          weight: 700
        - asset: assets/fonts/PPTelegraf-Ultrabold.otf
          weight: 800
        - asset: assets/fonts/PPTelegraf-Black.otf
          weight: 900
